// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: greeter/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_greeter_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_greeter_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetReply) Reset() {
	*x = GreetReply{}
	mi := &file_greeter_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetReply) ProtoMessage() {}

func (x *GreetReply) ProtoReflect() protoreflect.Message {
	mi := &file_greeter_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetReply.ProtoReflect.Descriptor instead.
func (*GreetReply) Descriptor() ([]byte, []int) {
	return file_greeter_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *GreetReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_greeter_v1_greeter_proto protoreflect.FileDescriptor

const file_greeter_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x18greeter/v1/greeter.proto\x12\n" +
	"greeter.v1\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\fGreetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"GreetReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2c\n" +
	"\aGreeter\x12X\n" +
	"\x05Greet\x12\x18.greeter.v1.GreetRequest\x1a\x16.greeter.v1.GreetReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/greeter/greet/{name}B#Z!kratos-tutorial/api/greeter/v1;v1b\x06proto3"

var (
	file_greeter_v1_greeter_proto_rawDescOnce sync.Once
	file_greeter_v1_greeter_proto_rawDescData []byte
)

func file_greeter_v1_greeter_proto_rawDescGZIP() []byte {
	file_greeter_v1_greeter_proto_rawDescOnce.Do(func() {
		file_greeter_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_greeter_v1_greeter_proto_rawDesc), len(file_greeter_v1_greeter_proto_rawDesc)))
	})
	return file_greeter_v1_greeter_proto_rawDescData
}

var file_greeter_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_greeter_v1_greeter_proto_goTypes = []any{
	(*GreetRequest)(nil), // 0: greeter.v1.GreetRequest
	(*GreetReply)(nil),   // 1: greeter.v1.GreetReply
}
var file_greeter_v1_greeter_proto_depIdxs = []int32{
	0, // 0: greeter.v1.Greeter.Greet:input_type -> greeter.v1.GreetRequest
	1, // 1: greeter.v1.Greeter.Greet:output_type -> greeter.v1.GreetReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_greeter_v1_greeter_proto_init() }
func file_greeter_v1_greeter_proto_init() {
	if File_greeter_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_greeter_v1_greeter_proto_rawDesc), len(file_greeter_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greeter_v1_greeter_proto_goTypes,
		DependencyIndexes: file_greeter_v1_greeter_proto_depIdxs,
		MessageInfos:      file_greeter_v1_greeter_proto_msgTypes,
	}.Build()
	File_greeter_v1_greeter_proto = out.File
	file_greeter_v1_greeter_proto_goTypes = nil
	file_greeter_v1_greeter_proto_depIdxs = nil
}
